// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArrozzGsVM8VxIlH_Ee2Q69fcwEstjQcg',
    appId: '1:424383632339:web:644434118579b1aa82d526',
    messagingSenderId: '424383632339',
    projectId: 'ecole-app-ce95a',
    authDomain: 'ecole-app-ce95a.firebaseapp.com',
    storageBucket: 'ecole-app-ce95a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6bKQRIxh09fX8vgil9AlP-xirxm8J_a4',
    appId: '1:424383632339:android:6a3813384bb111da82d526',
    messagingSenderId: '424383632339',
    projectId: 'ecole-app-ce95a',
    storageBucket: 'ecole-app-ce95a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAArylrGGwPmQD5cuIrnCkd5kZbGL0EFwo',
    appId: '1:424383632339:ios:c40c23816a12b19e82d526',
    messagingSenderId: '424383632339',
    projectId: 'ecole-app-ce95a',
    storageBucket: 'ecole-app-ce95a.firebasestorage.app',
    iosBundleId: 'com.example.ecoleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAArylrGGwPmQD5cuIrnCkd5kZbGL0EFwo',
    appId: '1:424383632339:ios:c40c23816a12b19e82d526',
    messagingSenderId: '424383632339',
    projectId: 'ecole-app-ce95a',
    storageBucket: 'ecole-app-ce95a.firebasestorage.app',
    iosBundleId: 'com.example.ecoleApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArrozzGsVM8VxIlH_Ee2Q69fcwEstjQcg',
    appId: '1:424383632339:web:829988c3962b14c282d526',
    messagingSenderId: '424383632339',
    projectId: 'ecole-app-ce95a',
    authDomain: 'ecole-app-ce95a.firebaseapp.com',
    storageBucket: 'ecole-app-ce95a.firebasestorage.app',
  );
}
